source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/ui.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/window_rule.conf

### ENVIRONMENT VARIABLES ###
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
