# Preload the wallpaper into memory
preload = ~/.config/hypr/wallpapers/moon.png

# Set the wallpaper for a specific monitor
# Syntax: wallpaper = <monitor>, <path/to/image>
wallpaper = DP-3, ~/.config/hypr/wallpapers/moon.png

# If you want the same wallpaper on all monitors, leave the monitor empty
wallpaper = , ~/.config/hypr/wallpapers/moon.png

