shadow-exclude = [
    "name = 'Notification'",
    "class_g = 'Conky'",
    "class_g ?= 'Notify-osd'",
    "class_g = 'Cairo-clock'",
    "_GTK_FRAME_EXTENTS@:c",
    # FIX: Exclude drag-and-drop windows
    "class_g = 'slop'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "window_type = 'dnd'",
    "window_type = 'tooltip'"
];

fade-exclude = [
  "window_type = 'dnd'",
  "window_type = 'tooltip'"
];

blur-background-exclude = [
  "window_type = 'dnd'",
  "window_type = 'tooltip'"
];

backend = "glx";
