[bar]
scale = 0.6700000166893005
rounding = "none"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
]
center = ["clock"]
right = [
    "netstat",
    "cpu",
    "ram",
    "bluetooth",
    "network",
    "volume",
    "notifications",
    "systray",
]

[styling]
scale = 0.699999988079071
rounding = "none"

[modules.battery]
icon-show = false
label-show = false

[modules.clock]
format = "%A, %b %d, %Y - %I:%M %p"

[modules.dashboard]
icon-bg-color = "#3584e4"

[modules.hyprland-workspaces]
icon-gap = 0.5
workspace-padding = 0.699999988079071
active-color = "#ed333b"

[modules.netstat]
format = "↓ {{ down_auto }}  -  ↑ {{ up_auto }}"

[modules.power]
icon-name = "ld-power-symbolic"
border-color = "red"
icon-color = "auto"
icon-bg-color = "blue"
left-click = "wlogout --protocol layer-shell"

[modules.ram]
format = "{{ used_gib }} GB | {{ total_gib }} GB"
