font_family      JetBrainsMono Nerd Font
italic_font      JetBrainsMono Nerd Font
bold_font        auto

modify_font cell_height -2px
font_size        13.0

window_padding_width 0
text_composition_strategy platform

