inherits = "kanagawa-dragon"

"ui.background" = { fg = "dragonWhite", bg = "dragonDarker" }
"ui.statusline" = { fg = "dragonWhite", bg = "popupBgLight" }
"ui.popup" = { fg = "dragonWhite", bg = "popupBgLight" }

"comment" = { fg = "darkGreen" }

[palette]
dragonDarker = "#0d0c0c"
darkGreen = "#3d6b3d"
popupBgLight = "#23211f"
