theme = "material_deep_ocean"

[editor]
line-number = "relative"
mouse = true
true-color = true
auto-format = false

[editor.lsp]
display-progress-messages = true
# enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
# git-ignore = false
# git-global = false
# git-exclude = false
# ignore = false

[editor.statusline]
left = ["mode", "separator", "version-control", "spacer", "separator", "spinner", "file-modification-indicator", "read-only-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│ "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

