[[language]]
name = "go"
auto-format = true
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "cmake"
language-servers = ["cmake-language-server"]

[[language]]
name = "c"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "cpp"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "javascript"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "typescript"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "json"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "jsonc"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[language-server.gopls.config]
gofumpt = false

[language-server.godot]
command = "ncat"
args = ["127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = ["godot"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
auto-format = false
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "css"
auto-format = false
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "jsx"
auto-format = false
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "tsx"
auto-format = false
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "svelte"
auto-format = false
language-servers = [ "svelteserver", "tailwindcss-ls" ]
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "wgsl"
auto-format = false
language-servers = ["wgsl-analyzer"]
file-types = ["wgsl"]
indent = { tab-width = 4, unit = "    "}
