shell=/bin/fish
login-shell=yes

term=xterm-256color

# Font
font=JetBrainsMono Nerd Font Mono:size=13
font-bold=JetBrainsMono Nerd Font Mono:style=Bold:size=13
font-italic=JetBrainsMono Nerd Font Mono:style=Medium:size=13
font-bold-italic=JetBrainsMono Nerd Font Mono:style=Bold:size=13

[environment]
TERM=xterm-256color

[colors-dark]
# Ayu Dark
alpha=0.95

background=0B0E14
foreground=BFBDB6

# Cursor
cursor=0B0E14 BFBDB6

# Normal colors
regular0=0B0E14
regular1=D95757
regular2=AAD94C
regular3=E6B450
regular4=59C2FF
regular5=D2A6FF
regular6=95E6CB
regular7=BFBDB6

# Bright colors
bright0=565B66
bright1=F07178
bright2=BAE67E
bright3=FFB454
bright4=73D0FF
bright5=D2A6FF
bright6=95E6CB
bright7=E6E1CF

[mouse]
hide-when-typing=yes
